### ISSUE TITLE
Packet Forwarder crashing out in AS923 region.

### ISSUE THREAD

**Issue by ryanteck** [NebraLtd/hm-pktfwd#15]
The latest update of the miner (GA 29th of May) introduced the new regions of AS923_1, AS923_2, AS923_3 and AS923_4

As no warning was given of this change the packet forwarder doesn't have a matching index for these variables (Nor I think a frequency plan for AS923_3 & AS923_4).

These new plans need to be added, then updated on the index.

**Comment by ryanteck** [comment]
Fixed in 2021.06.01.0

**Comment by marvinmarnold** [comment]
This is still happening a lot on Sentry https://sentry.io/organizations/nebra/issues/2427112266/?project=5730185&statsPeriod=30d

**Comment by shawaj** [comment]
What's the issue that's coming through in sentry @marvinmarnold ? Can't seem to log in

**Comment by marvinmarnold** [comment]
![Screen Shot 2022-05-03 at 5 11 51 PM](https://user-images.githubusercontent.com/1311030/166574663-b166b3da-6381-4be3-99c4-18e19dc775c2.png)

**Comment by shawaj** [comment]
That screenshot shows us915?

**Comment by marvinmarnold** [comment]
It's the same codepath so Sentry groups them together. Whenever the region is unknown.

**Comment by shawaj** [comment]
This seems like a miner that is not up to date. As key error for us915 / 923 implies outdated software (i.e. before we introduced those and it was just US915 without the region_ in front)

**Comment by pritamghanghas** [comment]
sentry screenshots in case the sentry link is broken:
![Screenshot from 2022-05-13 21-16-03](https://user-images.githubusercontent.com/6928727/168325172-6b234d23-6ebf-4b07-9126-2551a95c8535.png)
![Screenshot from 2022-05-13 21-16-05](https://user-images.githubusercontent.com/6928727/168325181-c1edff61-2499-44a9-84f1-bfee35dca3d4.png)
![Screenshot from 2022-05-13 21-16-07](https://user-images.githubusercontent.com/6928727/168325182-177d5efa-3ae5-42e5-a617-559c996d857b.png)
